### ISSUE TITLE
Unknow file in the main.py

### ISSUE THREAD

**Issue by elpicio** [workingcoder/MCJA#2]
There is an unknow file in the **main.py, line 238**" perm = sio.loadmat(os.path.join(cfg.data_root, 'exp', 'rand_perm_cam.mat'))['rand_perm_cam']". The file "rand_perm_cam.mat" seems like in the floder of sysu dataset called 'exp', but I don't find it in the offical dataset of SYSU-MM01. Is this your original code? It seems that I cannot run your code without this file.
![image](https://github.com/workingcoder/MCJA/assets/74490767/7ad6d823-b37b-4d7f-af8a-e1c720c0614a)

**Comment by workingcoder** [comment]
This file originates from an official dataset (https://github.com/wuancong/SYSU-MM01/blob/master/evaluation/data_split/rand_perm_cam.mat), and most existing methods utilize this configuration. Thus, we just adopted the same setup for comparison.

**Comment by elpicio** [comment]
> This file originates from an official dataset (https://github.com/wuancong/SYSU-MM01/blob/master/evaluation/data_split/rand_perm_cam.mat), and most existing methods utilize this configuration. Thus, we just adopted the same setup for comparison.

Thank you for your reply. I find that file successfully
